title: The Liverpool New Robotic Telescope
remote-theme: "mmistakes/minimal-mistakes"
docs_list_title: ACME Documentation
docs:

- title: Introduction
  url: ed.md

- title: Configuration
  url: team.md

- title: Deployment
  url: news.md

